# Generated by Django 5.0.2 on 2024-02-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_de_produit', models.CharField(max_length=100)),
                ('poids', models.CharField(max_length=50)),
                ('quantite', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.IntegerField()),
                ('imageProduit1', models.ImageField(upload_to='img1')),
                ('imageProduit2', models.ImageField(blank=True, null=True, upload_to='img2')),
                ('imageProduit3', models.ImageField(blank=True, null=True, upload_to='img3')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_sur', models.CharField(blank=True, max_length=100, null=True)),
                ('reduction', models.IntegerField(blank=True, null=True)),
                ('date_fin_promo', models.DateField(blank=True, null=True)),
                ('quantite', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
